image: docker:latest
# services:
#   - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - build

docker-build:
  stage: build
  script:
  - ls -l
  - docker build -t test-app .
  - docker tag test-app registry.-dev:5000/test-app
  - docker push registry-dev:5000/test-app
